#!/bin/sh
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP300_LSP1_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP400_LSP1_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP500_LSP100_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP500_LSP1_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP500_LSP200_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP500_LSP300_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP600_LSP1_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP600_LSP200_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP600_LSP300_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP600_LSP400_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP800_LSP1_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP800_LSP200_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP800_LSP300_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP800_LSP400_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP800_LSP500_Autumn18_Private_0_RA2AnalysisTree.root")'
root -l -q 'checkTree.C("/eos/uscms/store/user/vhegde/RA2bTrees_V17/EW_SUSY/Autumn18Fast.TChiWH_NLSP800_LSP600_Autumn18_Private_0_RA2AnalysisTree.root")'
